# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Run Java Test Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin' # See 'Supported distributions' for available options

    - name: Check Java Version
      run: java --version
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Test with Gradle
      run: ./gradlew test
    #--info test
    # - name: Run JUnit Tests
    #   run: java -jar lib/junit-platform-console-standalone-1.10.0.jar --class-path . --scan-classpath

